In [5]:
import pandas as pd
import numpy as np
import tensorflow as tf

In [6]:
df=pd.read_csv(r"C:\Users\aisha\OneDrive\Desktop\Naresh IT\OCT\12th,- ENSAMBLE LEARNING\CHURN MODELING- TF\Churn_Modelling.csv")
df

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [7]:
df.head(4)

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0

In [8]:
X = df.iloc[:,3:-1].values
y = df.iloc[:,-1].values

In [10]:
X

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]],
      shape=(10000, 10), dtype=object)

In [11]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:,2] = le.fit_transform(X[:,2])

In [12]:
X

array([[619, 'France', 0, ..., 1, 1, 101348.88],
       [608, 'Spain', 0, ..., 0, 1, 112542.58],
       [502, 'France', 0, ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 0, ..., 0, 1, 42085.58],
       [772, 'Germany', 1, ..., 1, 0, 92888.52],
       [792, 'France', 0, ..., 1, 0, 38190.78]],
      shape=(10000, 10), dtype=object)

In [13]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[1])],remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [14]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X = sc.fit_transform(X)

In [15]:
X

array([[ 0.99720391, -0.57873591, -0.57380915, ...,  0.64609167,
         0.97024255,  0.02188649],
       [-1.00280393, -0.57873591,  1.74273971, ..., -1.54776799,
         0.97024255,  0.21653375],
       [ 0.99720391, -0.57873591, -0.57380915, ...,  0.64609167,
        -1.03067011,  0.2406869 ],
       ...,
       [ 0.99720391, -0.57873591, -0.57380915, ..., -1.54776799,
         0.97024255, -1.00864308],
       [-1.00280393,  1.72790383, -0.57380915, ...,  0.64609167,
        -1.03067011, -0.12523071],
       [ 0.99720391, -0.57873591, -0.57380915, ...,  0.64609167,
        -1.03067011, -1.07636976]], shape=(10000, 12))

In [16]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.20, random_state=0)

In [17]:
ann = tf.keras.models.Sequential()

ann.add(tf.keras.layers.Dense(units = 6,activation = 'relu'))
ann.add(tf.keras.layers.Dense(units = 6,activation = 'relu'))
ann.add(tf.keras.layers.Dense(units = 5,activation = 'relu'))
ann.add(tf.keras.layers.Dense(units = 4,activation = 'relu'))
ann.add(tf.keras.layers.Dense(units = 1,activation = 'sigmoid'))

In [18]:
ann.compile(optimizer = 'adam',loss = 'binary_crossentropy',metrics = ['accuracy'])

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.

In [19]:
ann.fit(X_train,y_train,batch_size = 32,epochs = 150,validation_data=(X_test,y_test))

Epoch 1/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 6s 8ms/step - accuracy: 0.7960 - loss: 0.5537 - val_accuracy: 0.7975 - val_loss: 0.4956
Epoch 2/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.7960 - loss: 0.4775 - val_accuracy: 0.7975 - val_loss: 0.4598
Epoch 3/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.7960 - loss: 0.4506 - val_accuracy: 0.7975 - val_loss: 0.4432
Epoch 4/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.7960 - loss: 0.4379 - val_accuracy: 0.7975 - val_loss: 0.4366
Epoch 5/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.7960 - loss: 0.4308 - val_accuracy: 0.7975 - val_loss: 0.4333
Epoch 6/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.7960 - loss: 0.4244 - val_accuracy: 0.7975 - val_loss: 0.4227
Epoch 7/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.7960 - loss: 0.4174 - val_accuracy: 0.7975 - val_loss: 0.4137
Epoch 8/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.7960 - loss: 0.4104 - val_accuracy: 0.7975 - val_loss: 0.4043
Epoch 9/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.8016 - loss: 0.4043 - val_accuracy: 0.8110 - val_loss: 0.3968
Epoch 10/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.8101 - loss: 0.3997 - val_accuracy: 0.8150 - val_loss: 0.3948
Epoch 11/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.8163 - loss: 0.3960 - val_accuracy: 0.8225 - val_loss: 0.3902
Epoch 12/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8188 - loss: 0.3913 - val_accuracy: 0.8270 - val_loss: 0.3868
Epoch 13/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.8241 - loss: 0.3878 - val_accuracy: 0.8320 - val_loss: 0.3826
Epoch 14/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.8315 - loss: 0.3846 - val_accuracy: 0.8375 - val_loss: 0.3777
Epoch 15/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.8304 - loss: 0.3827 - val_accuracy: 0.8335 - val_loss: 0.3791
Epoch 16/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8355 - loss: 0.3802 - val_accuracy: 0.8325 - val_loss: 0.3772
Epoch 17/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8365 - loss: 0.3780 - val_accuracy: 0.8360 - val_loss: 0.3764
Epoch 18/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.8385 - loss: 0.3764 - val_accuracy: 0.8410 - val_loss: 0.3704
Epoch 19/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.8432 - loss: 0.3748 - val_accuracy: 0.8435 - val_loss: 0.3693
Epoch 20/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8428 - loss: 0.3727 - val_accuracy: 0.8420 - val_loss: 0.3674
Epoch 21/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.8485 - loss: 0.3707 - val_accuracy: 0.8455 - val_loss: 0.3651
Epoch 22/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8499 - loss: 0.3681 - val_accuracy: 0.8485 - val_loss: 0.3599
Epoch 23/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8500 - loss: 0.3651 - val_accuracy: 0.8525 - val_loss: 0.3601
Epoch 24/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.8546 - loss: 0.3628 - val_accuracy: 0.8610 - val_loss: 0.3541
Epoch 25/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.8556 - loss: 0.3602 - val_accuracy: 0.8585 - val_loss: 0.3519
Epoch 26/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.8594 - loss: 0.3570 - val_accuracy: 0.8600 - val_loss: 0.3481
Epoch 27/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.8594 - loss: 0.3551 - val_accuracy: 0.8585 - val_loss: 0.3475
Epoch 28/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.8604 - loss: 0.3528 - val_accuracy: 0.8590 - val_loss: 0.3457
Epoch 29/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.8605 - loss: 0.3513 - val_accuracy: 0.8595 - val_loss: 0.3443
Epoch 30/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8594 - loss: 0.3494 - val_accuracy: 0.8630 - val_loss: 0.3414
Epoch 31/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8604 - loss: 0.3482 - val_accuracy: 0.8600 - val_loss: 0.3444
Epoch 32/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8618 - loss: 0.3465 - val_accuracy: 0.8620 - val_loss: 0.3397
Epoch 33/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.8618 - loss: 0.3461 - val_accuracy: 0.8645 - val_loss: 0.3409
Epoch 34/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.8616 - loss: 0.3455 - val_accuracy: 0.8630 - val_loss: 0.3416
Epoch 35/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.8624 - loss: 0.3446 - val_accuracy: 0.8640 - val_loss: 0.3388
Epoch 36/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.8639 - loss: 0.3439 - val_accuracy: 0.8595 - val_loss: 0.3417
Epoch 37/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.8618 - loss: 0.3434 - val_accuracy: 0.8630 - val_loss: 0.3378
Epoch 38/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - accuracy: 0.8618 - loss: 0.3426 - val_accuracy: 0.8625 - val_loss: 0.3393
Epoch 39/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8615 - loss: 0.3422 - val_accuracy: 0.8625 - val_loss: 0.3370
Epoch 40/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - accuracy: 0.8616 - loss: 0.3413 - val_accuracy: 0.8620 - val_loss: 0.3398
Epoch 41/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.8633 - loss: 0.3415 - val_accuracy: 0.8640 - val_loss: 0.3380
Epoch 42/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8615 - loss: 0.3409 - val_accuracy: 0.8655 - val_loss: 0.3372
Epoch 43/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8610 - loss: 0.3403 - val_accuracy: 0.8650 - val_loss: 0.3361
Epoch 44/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.8619 - loss: 0.3403 - val_accuracy: 0.8630 - val_loss: 0.3372
Epoch 45/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.8637 - loss: 0.3395 - val_accuracy: 0.8615 - val_loss: 0.3362
Epoch 46/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8616 - loss: 0.3388 - val_accuracy: 0.8640 - val_loss: 0.3355
Epoch 47/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.8636 - loss: 0.3387 - val_accuracy: 0.8645 - val_loss: 0.3376
Epoch 48/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.8631 - loss: 0.3386 - val_accuracy: 0.8625 - val_loss: 0.3377
Epoch 49/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - accuracy: 0.8633 - loss: 0.3377 - val_accuracy: 0.8650 - val_loss: 0.3362
Epoch 50/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8630 - loss: 0.3376 - val_accuracy: 0.8650 - val_loss: 0.3361
Epoch 51/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.8626 - loss: 0.3374 - val_accuracy: 0.8635 - val_loss: 0.3358
Epoch 52/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.8655 - loss: 0.3374 - val_accuracy: 0.8645 - val_loss: 0.3343
Epoch 53/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.8631 - loss: 0.3371 - val_accuracy: 0.8635 - val_loss: 0.3350
Epoch 54/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.8645 - loss: 0.3364 - val_accuracy: 0.8635 - val_loss: 0.3360
Epoch 55/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.8625 - loss: 0.3362 - val_accuracy: 0.8665 - val_loss: 0.3349
Epoch 56/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.8640 - loss: 0.3360 - val_accuracy: 0.8640 - val_loss: 0.3341
Epoch 57/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8644 - loss: 0.3363 - val_accuracy: 0.8630 - val_loss: 0.3350
Epoch 58/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.8639 - loss: 0.3360 - val_accuracy: 0.8595 - val_loss: 0.3356
Epoch 59/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.8630 - loss: 0.3353 - val_accuracy: 0.8605 - val_loss: 0.3364
Epoch 60/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8643 - loss: 0.3350 - val_accuracy: 0.8600 - val_loss: 0.3342
Epoch 61/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.8627 - loss: 0.3345 - val_accuracy: 0.8600 - val_loss: 0.3376
Epoch 62/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - accuracy: 0.8629 - loss: 0.3351 - val_accuracy: 0.8635 - val_loss: 0.3346
Epoch 63/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8624 - loss: 0.3344 - val_accuracy: 0.8620 - val_loss: 0.3355
Epoch 64/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.8622 - loss: 0.3341 - val_accuracy: 0.8640 - val_loss: 0.3347
Epoch 65/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8641 - loss: 0.3341 - val_accuracy: 0.8595 - val_loss: 0.3370
Epoch 66/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.8629 - loss: 0.3334 - val_accuracy: 0.8625 - val_loss: 0.3338
Epoch 67/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.8629 - loss: 0.3342 - val_accuracy: 0.8640 - val_loss: 0.3341
Epoch 68/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8630 - loss: 0.3340 - val_accuracy: 0.8605 - val_loss: 0.3351
Epoch 69/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.8626 - loss: 0.3339 - val_accuracy: 0.8650 - val_loss: 0.3342
Epoch 70/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8641 - loss: 0.3335 - val_accuracy: 0.8580 - val_loss: 0.3377
Epoch 71/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8635 - loss: 0.3332 - val_accuracy: 0.8620 - val_loss: 0.3331
Epoch 72/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8648 - loss: 0.3332 - val_accuracy: 0.8630 - val_loss: 0.3335
Epoch 73/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.8643 - loss: 0.3332 - val_accuracy: 0.8610 - val_loss: 0.3348
Epoch 74/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.8633 - loss: 0.3325 - val_accuracy: 0.8610 - val_loss: 0.3354
Epoch 75/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8640 - loss: 0.3323 - val_accuracy: 0.8655 - val_loss: 0.3336
Epoch 76/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8639 - loss: 0.3324 - val_accuracy: 0.8625 - val_loss: 0.3352
Epoch 77/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.8624 - loss: 0.3329 - val_accuracy: 0.8590 - val_loss: 0.3362
Epoch 78/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.8641 - loss: 0.3321 - val_accuracy: 0.8595 - val_loss: 0.3355
Epoch 79/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8631 - loss: 0.3319 - val_accuracy: 0.8600 - val_loss: 0.3346
Epoch 80/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8633 - loss: 0.3318 - val_accuracy: 0.8620 - val_loss: 0.3329
Epoch 81/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.8660 - loss: 0.3319 - val_accuracy: 0.8640 - val_loss: 0.3338
Epoch 82/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - accuracy: 0.8651 - loss: 0.3316 - val_accuracy: 0.8625 - val_loss: 0.3334
Epoch 83/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8633 - loss: 0.3315 - val_accuracy: 0.8560 - val_loss: 0.3403
Epoch 84/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - accuracy: 0.8640 - loss: 0.3316 - val_accuracy: 0.8660 - val_loss: 0.3329
Epoch 85/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8625 - loss: 0.3318 - val_accuracy: 0.8620 - val_loss: 0.3327
Epoch 86/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.8645 - loss: 0.3309 - val_accuracy: 0.8640 - val_loss: 0.3335
Epoch 87/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.8627 - loss: 0.3309 - val_accuracy: 0.8625 - val_loss: 0.3332
Epoch 88/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - accuracy: 0.8637 - loss: 0.3308 - val_accuracy: 0.8630 - val_loss: 0.3317
Epoch 89/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8645 - loss: 0.3306 - val_accuracy: 0.8590 - val_loss: 0.3358
Epoch 90/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.8645 - loss: 0.3309 - val_accuracy: 0.8640 - val_loss: 0.3317
Epoch 91/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.8648 - loss: 0.3310 - val_accuracy: 0.8660 - val_loss: 0.3328
Epoch 92/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.8645 - loss: 0.3304 - val_accuracy: 0.8665 - val_loss: 0.3323
Epoch 93/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.8652 - loss: 0.3308 - val_accuracy: 0.8650 - val_loss: 0.3318
Epoch 94/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.8658 - loss: 0.3301 - val_accuracy: 0.8610 - val_loss: 0.3350
Epoch 95/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.8627 - loss: 0.3308 - val_accuracy: 0.8630 - val_loss: 0.3315
Epoch 96/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8652 - loss: 0.3298 - val_accuracy: 0.8645 - val_loss: 0.3329
Epoch 97/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8648 - loss: 0.3308 - val_accuracy: 0.8620 - val_loss: 0.3329
Epoch 98/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.8643 - loss: 0.3302 - val_accuracy: 0.8650 - val_loss: 0.3312
Epoch 99/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.8660 - loss: 0.3299 - val_accuracy: 0.8640 - val_loss: 0.3315
Epoch 100/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.8664 - loss: 0.3294 - val_accuracy: 0.8605 - val_loss: 0.3344
Epoch 101/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.8669 - loss: 0.3290 - val_accuracy: 0.8670 - val_loss: 0.3328
Epoch 102/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - accuracy: 0.8622 - loss: 0.3303 - val_accuracy: 0.8580 - val_loss: 0.3355
Epoch 103/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8633 - loss: 0.3297 - val_accuracy: 0.8625 - val_loss: 0.3314
Epoch 104/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.8660 - loss: 0.3292 - val_accuracy: 0.8630 - val_loss: 0.3327
Epoch 105/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.8635 - loss: 0.3296 - val_accuracy: 0.8640 - val_loss: 0.3320
Epoch 106/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.8656 - loss: 0.3289 - val_accuracy: 0.8635 - val_loss: 0.3331
Epoch 107/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.8644 - loss: 0.3291 - val_accuracy: 0.8645 - val_loss: 0.3313
Epoch 108/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.8659 - loss: 0.3293 - val_accuracy: 0.8625 - val_loss: 0.3324
Epoch 109/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8650 - loss: 0.3294 - val_accuracy: 0.8645 - val_loss: 0.3328
Epoch 110/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8655 - loss: 0.3292 - val_accuracy: 0.8615 - val_loss: 0.3324
Epoch 111/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8670 - loss: 0.3288 - val_accuracy: 0.8635 - val_loss: 0.3329
Epoch 112/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8658 - loss: 0.3285 - val_accuracy: 0.8650 - val_loss: 0.3310
Epoch 113/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.8645 - loss: 0.3288 - val_accuracy: 0.8645 - val_loss: 0.3319
Epoch 114/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8659 - loss: 0.3285 - val_accuracy: 0.8640 - val_loss: 0.3324
Epoch 115/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.8656 - loss: 0.3286 - val_accuracy: 0.8655 - val_loss: 0.3309
Epoch 116/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.8648 - loss: 0.3293 - val_accuracy: 0.8645 - val_loss: 0.3311
Epoch 117/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.8649 - loss: 0.3286 - val_accuracy: 0.8640 - val_loss: 0.3310
Epoch 118/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8645 - loss: 0.3284 - val_accuracy: 0.8655 - val_loss: 0.3321
Epoch 119/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8658 - loss: 0.3278 - val_accuracy: 0.8555 - val_loss: 0.3385
Epoch 120/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.8644 - loss: 0.3282 - val_accuracy: 0.8650 - val_loss: 0.3316
Epoch 121/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8651 - loss: 0.3284 - val_accuracy: 0.8590 - val_loss: 0.3353
Epoch 122/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8658 - loss: 0.3281 - val_accuracy: 0.8630 - val_loss: 0.3334
Epoch 123/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8664 - loss: 0.3278 - val_accuracy: 0.8610 - val_loss: 0.3340
Epoch 124/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8655 - loss: 0.3279 - val_accuracy: 0.8640 - val_loss: 0.3318
Epoch 125/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.8641 - loss: 0.3279 - val_accuracy: 0.8645 - val_loss: 0.3313
Epoch 126/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8669 - loss: 0.3276 - val_accuracy: 0.8620 - val_loss: 0.3336
Epoch 127/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8651 - loss: 0.3280 - val_accuracy: 0.8660 - val_loss: 0.3328
Epoch 128/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8648 - loss: 0.3281 - val_accuracy: 0.8605 - val_loss: 0.3347
Epoch 129/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8639 - loss: 0.3286 - val_accuracy: 0.8620 - val_loss: 0.3330
Epoch 130/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - accuracy: 0.8648 - loss: 0.3280 - val_accuracy: 0.8570 - val_loss: 0.3396
Epoch 131/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8658 - loss: 0.3280 - val_accuracy: 0.8610 - val_loss: 0.3323
Epoch 132/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.8639 - loss: 0.3278 - val_accuracy: 0.8655 - val_loss: 0.3331
Epoch 133/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8658 - loss: 0.3273 - val_accuracy: 0.8645 - val_loss: 0.3310
Epoch 134/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.8659 - loss: 0.3275 - val_accuracy: 0.8660 - val_loss: 0.3330
Epoch 135/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8660 - loss: 0.3280 - val_accuracy: 0.8660 - val_loss: 0.3333
Epoch 136/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.8662 - loss: 0.3275 - val_accuracy: 0.8630 - val_loss: 0.3319
Epoch 137/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.8658 - loss: 0.3279 - val_accuracy: 0.8670 - val_loss: 0.3313
Epoch 138/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8661 - loss: 0.3275 - val_accuracy: 0.8585 - val_loss: 0.3367
Epoch 139/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.8649 - loss: 0.3279 - val_accuracy: 0.8625 - val_loss: 0.3317
Epoch 140/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.8656 - loss: 0.3275 - val_accuracy: 0.8615 - val_loss: 0.3319
Epoch 141/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.8652 - loss: 0.3279 - val_accuracy: 0.8635 - val_loss: 0.3313
Epoch 142/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.8654 - loss: 0.3270 - val_accuracy: 0.8620 - val_loss: 0.3319
Epoch 143/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8640 - loss: 0.3272 - val_accuracy: 0.8635 - val_loss: 0.3324
Epoch 144/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.8665 - loss: 0.3276 - val_accuracy: 0.8610 - val_loss: 0.3337
Epoch 145/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8664 - loss: 0.3266 - val_accuracy: 0.8615 - val_loss: 0.3335
Epoch 146/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8669 - loss: 0.3273 - val_accuracy: 0.8620 - val_loss: 0.3351
Epoch 147/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8668 - loss: 0.3268 - val_accuracy: 0.8620 - val_loss: 0.3318
Epoch 148/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8661 - loss: 0.3270 - val_accuracy: 0.8640 - val_loss: 0.3315
Epoch 149/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8671 - loss: 0.3272 - val_accuracy: 0.8550 - val_loss: 0.3393
Epoch 150/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8658 - loss: 0.3271 - val_accuracy: 0.8590 - val_loss: 0.3372

In [26]:
y_pred = ann.predict(X_test)

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step

In [27]:
y_pred = (y_pred > 0.5)

In [20]:
y_pred = ann.predict(X_test)

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step

In [28]:
print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),axis = 1))

[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]

In [29]:
from sklearn.metrics import accuracy_score,confusion_matrix
ac=accuracy_score(y_test,y_pred)
ac

0.859

In [30]:
cm = confusion_matrix(y_test,y_pred)
cm

array([[1494,  101],
       [ 181,  224]])